// Static 8-month curriculum definition. IDs are stable strings used as keys
// in the persisted progress store.

export type LectureDef = { id: string; title: string; minutes: number };
export type ModuleDef = { id: string; title: string; lectures: LectureDef[] };
export type CourseDef = { id: string; title: string; modules: ModuleDef[] };
export type ProjectDef = {
  id: string;
  title: string;
  description: string;
  difficulty: "Easy" | "Medium" | "Hard";
  estimatedHours: number;
  skills: string[];
  requirements: string[];
};
export type QuestionDef = {
  id: string;
  category: string;
  type: "mcq" | "open";
  question: string;
  options?: string[];
  answerIndex?: number;
};
export type AssessmentDef = { id: string; title: string; questions: QuestionDef[] };
export type MonthDef = {
  id: number;
  title: string;
  subtitle: string;
  description: string;
  courses: CourseDef[];
  assessment?: AssessmentDef;
  project?: ProjectDef;
};

const mkLectures = (prefix: string, items: [string, number][]): LectureDef[] =>
  items.map(([title, minutes], i) => ({ id: `${prefix}-l${i + 1}`, title, minutes }));

const mkModule = (prefix: string, title: string, items: [string, number][]): ModuleDef => ({
  id: prefix,
  title,
  lectures: mkLectures(prefix, items),
});

// ---------- ASSESSMENTS ----------
const jsQuestions: QuestionDef[] = [
  {
    id: "q1",
    category: "Closures",
    type: "mcq",
    question: "What is a closure in JavaScript?",
    options: [
      "A function bundled with its lexical scope",
      "A way to close a browser tab",
      "A loop construct",
      "A type of object",
    ],
    answerIndex: 0,
  },
  {
    id: "q2",
    category: "Hoisting",
    type: "mcq",
    question: "Which of these are hoisted?",
    options: [
      "let and const",
      "var and function declarations",
      "class declarations",
      "import statements",
    ],
    answerIndex: 1,
  },
  {
    id: "q3",
    category: "Scope",
    type: "mcq",
    question: "What scope does `let` use?",
    options: ["Function", "Global only", "Block", "Module"],
    answerIndex: 2,
  },
  {
    id: "q4",
    category: "Promises",
    type: "mcq",
    question: "What does Promise.all reject with?",
    options: ["All errors", "The first error", "Undefined", "An array of errors"],
    answerIndex: 1,
  },
  {
    id: "q5",
    category: "Async/Await",
    type: "mcq",
    question: "`await` can be used at top level in...",
    options: ["CommonJS", "Any file", "ES Modules", "Never"],
    answerIndex: 2,
  },
  {
    id: "q6",
    category: "Objects",
    type: "mcq",
    question: "Object.freeze does what?",
    options: ["Deep freezes", "Shallow freezes", "Locks types", "Nothing"],
    answerIndex: 1,
  },
  {
    id: "q7",
    category: "Arrays",
    type: "mcq",
    question: "Which mutates the array?",
    options: ["map", "filter", "splice", "slice"],
    answerIndex: 2,
  },
  {
    id: "q8",
    category: "Functions",
    type: "mcq",
    question: "Arrow functions...",
    options: ["Have their own `this`", "Bind `this` lexically", "Cannot be async", "Cannot return"],
    answerIndex: 1,
  },
  {
    id: "q9",
    category: "DOM",
    type: "mcq",
    question: "querySelectorAll returns?",
    options: ["HTMLCollection", "NodeList", "Array", "Element"],
    answerIndex: 1,
  },
  {
    id: "q10",
    category: "Events",
    type: "mcq",
    question: "Event bubbling means...",
    options: [
      "Events go child→parent",
      "Events go parent→child",
      "Events disappear",
      "Events repeat",
    ],
    answerIndex: 0,
  },
  {
    id: "q11",
    category: "ES6",
    type: "mcq",
    question: "Spread operator is...",
    options: ["..", "...", "**", "&&"],
    answerIndex: 1,
  },
  {
    id: "q12",
    category: "Modules",
    type: "mcq",
    question: "Default export per module?",
    options: ["0", "1", "Many", "Unlimited"],
    answerIndex: 1,
  },
  {
    id: "q13",
    category: "Closures",
    type: "mcq",
    question: "Closures are commonly used for...",
    options: ["Loops", "Data privacy", "Imports", "Casts"],
    answerIndex: 1,
  },
  {
    id: "q14",
    category: "Async/Await",
    type: "mcq",
    question: "An async function returns?",
    options: ["Value", "Promise", "Generator", "Iterator"],
    answerIndex: 1,
  },
  {
    id: "q15",
    category: "Arrays",
    type: "mcq",
    question: "reduce signature is?",
    options: ["(acc, val) => acc", "(val) => val", "(val, acc) => val", "no args"],
    answerIndex: 0,
  },
  {
    id: "q16",
    category: "Open",
    type: "open",
    question: "Explain the event loop in your own words.",
  },
  {
    id: "q17",
    category: "Open",
    type: "open",
    question: "When would you prefer a Map over a plain object?",
  },
  { id: "q18", category: "Open", type: "open", question: "Describe debouncing vs throttling." },
  { id: "q19", category: "Open", type: "open", question: "How does prototypal inheritance work?" },
  {
    id: "q20",
    category: "Open",
    type: "open",
    question: "What pitfalls come with `this` in callbacks?",
  },
];

// Replicate to ~40 by mirroring categories for breadth
const buildAssessment = (base: QuestionDef[], topic: string): AssessmentDef => {
  const more: QuestionDef[] = base.slice(0, 20).map((q, i) => ({
    ...q,
    id: `${q.id}-b`,
    question: `(${topic}) ${q.question}`,
  }));
  return {
    id: `assess-${topic.toLowerCase()}`,
    title: `${topic} Interview Assessment`,
    questions: [...base, ...more],
  };
};

// ---------- MONTHS ----------
export const MONTHS: MonthDef[] = [
  {
    id: 1,
    title: "JavaScript Course",
    subtitle: "From Zero to Expert",
    description:
      "The modern JavaScript course for everyone! Master JavaScript with projects, challenges and theory. Many courses in one!",
    courses: [
      {
        id: "js-course",
        title: "The Complete JavaScript Course 2025: From Zero to Expert!",
        modules: [
          mkModule("js-fund", "Section 1: Welcome", [
            ["Course Structure and Projects", 22],
            ["Read Before You Start!", 28],
            ["Watch Before You Start!", 25],
            ["Setting Up Our Code Editor", 35],
          ]),
          mkModule("js-arrays", "Section 2: JS Fundamentals - Part 1", [
            ["Section Intro", 40],
            ["Hello World!", 30],
            ["A Brief Introduction to JavaScript", 25],
            ["Linking a JavaScript File", 22],
            ["Values and Variables", 18],
            ["Practice Assignments", 18],
            ["Data Types", 18],
            ["let, const and var", 18],
            ["Basic Operators", 18],
            ["Operator Precedence", 18],
            ["A Note About Challenges", 18],
            ["Strings and Template Literals", 18],
            ["Taking Decisions: if / else Statements", 18],
            ["Type Conversion and Coercion", 18],
            ["Truthy and Falsy Values", 18],
            ["Equality Operators: == vs. ===", 16],
            ["Boolean Logic", 9],
            ["Logical Operators", 11],
            ["CHALLENGE #3", 18],
            ["CHALLENGE #3: Video Solution", 12],
            ["The switch Statement", 13],
            ["Statements and Expressions", 6],
            ["The Conditional (Ternary) Operator", 10],
            ["CHALLENGE #4", 18],
            ["CHALLENGE #4: Video Solution", 6],
            ["JavaScript Releases: ES5, ES6+ and ESNext", 14],
            ["Section Summary PDF", 5],
          ]),
          mkModule("js-dom", "Section 3: JS Fundamentals - Part 2", [
            ["Activating Strict Mode", 10],
            ["Functions", 19],
            ["Function Declarations vs. Expressions", 11],
            ["Arrow Functions", 10],
            ["Functions Calling Other Functions", 10],
            ["Reviewing Functions", 16],
            ["CHALLENGE #1", 18],
            ["CHALLENGE #1: Video Solution", 14],
            ["Introduction to Arrays", 22],
            ["Basic Array Operations (Methods)", 13],
            ["CHALLENGE #2", 18],
            ["CHALLENGE #2: Video Solution", 7],
            ["Introduction to Objects", 6],
            ["Dot vs. Bracket Notation", 19],
            ["Object Methods", 23],
            ["CHALLENGE #3", 18],
            ["CHALLENGE #3: Video Solution", 10],
            ["Iteration: The for Loop", 11],
            ["Looping Arrays, Breaking and Continuing", 22],
            ["Looping Backwards and Loops in Loops", 12],
            ["The while Loop", 12],
            ["CHALLENGE #4", 18],
            ["CHALLENGE #4: Video Solution", 11],
            ["Section Summary PDF", 1],
          ]),
          mkModule("js-async", "Section 4: How to Navigate this course", [
            ["Pathways and Section Roadmaps", 4],
            ["Course Pathways", 1],
          ]),
          mkModule("js-oop", "Section 5: Developer Skills & Editor Setup", [
            ["Section Roadmap", 1],
            ["Setting up Prettier and VS Code", 16],
            ["Installing Node.js and Setting Up a Dev Environment", 12],
            ["Learning How to Code", 18],
            ["Help Mike Learn How to Code", 18],
            ["How to Think Like a Developer: Become a Problem Solver!", 11],
            ["Help Sofia Think Like a Developer", 18],
            ["Using Google, StackOverflow and MDN", 27],
            ["Debugging (Fixing Errors)", 5],
            ["Debugging with the Console and Breakpoints", 19],
            ["CHALLENGE #1", 15],
            ["The Rise of AI Tools (ChatGPT, Copilot, Cursor AI, etc.)", 18],
            ["Solving CHALLENGE #2 With AI", 17],
          ]),
          mkModule("js-oop", "Section 6: HTML & CSS Crash Course", [
            ["Section Intro", 1],
            ["Basic HTML Structure and Elements", 10],
            ["Attributes, Classes and IDs", 13],
            ["Basic Styling with CSS", 12],
            ["Introduction to the CSS Box Model", 21],
          ]),
          mkModule("js-oop", "Section 7: JavaScript in the Browser: DOM and Events [PROJECT]", [
            ["Section Roadmap", 1],
            ["PROJECT #1: Guess My Number!", 9],
            ["What's the DOM and DOM Manipulation", 7],
            ["Selecting and Manipulating Elements", 8],
            ["Handling Click Events", 13],
            ["Implementing the Game Logic", 20],
            ["Manipulating CSS Styles", 8],
            ["CHALLENGE #1", 12],
            ["Implementing Highscores", 8],
            ["Refactoring Our Code: The DRY Principle", 15],
            ["PROJECT #2: Modal Window", 13],
            ["Working With Classes", 17],
            ['Handling an "Esc" Keypress Event', 14],
            ["PROJECT #3: Pig Game", 17],
            ["Rolling the Dice", 16],
            ["Switching the Active Player", 15],
            ["Holding Current Score", 25],
            ["Resetting the Game", 16],
          ]),
          mkModule("js-oop", "Section 8: How JavaScript Works Behind the Scenes", [
            ["Section Roadmap", 1],
            ["An High-Level Overview of JavaScript", 12],
            ["The JavaScript Engine and Runtime", 14],
            ["Execution Contexts and The Call Stack", 18],
            ["Scope and The Scope Chain", 26],
            ["Scoping in Practice", 21],
            ["Variable Environment: Hoisting and The TDZ", 11],
            ["Hoisting and TDZ in Practice", 15],
            ["The this Keyword", 7],
            ["The this Keyword in Practice", 13],
            ["Regular Functions vs. Arrow Functions", 18],
            ["Memory Management: Primitives vs. Objects", 14],
            ["Object References in Practice (Shallow vs. Deep Copies)", 21],
            ["Memory Management: Garbage Collection", 15],
          ]),
          mkModule("js-oop", "Section 9: Data Structures, Modern Operators and Strings", [
            ["Section Intro", 1],
            ["Section Roadmap", 1],
            ["Destructuring Arrays", 20],
            ["Practice Assignments", 1],
            ["Destructuring Objects", 20],
            ["The Spread Operator (...)", 21],
            ["Rest Pattern and Parameters", 19],
            ["Short Circuiting (&& and ||)", 16],
            ["The Nullish Coalescing Operator (??)", 4],
            ["Logical Assignment Operators", 12],
            ["CHALLENGE #1", 15],
            ["Looping Arrays: The for-of Loop", 7],
            ["Enhanced Object Literals", 7],
            ["Optional Chaining (?.)", 16],
            ["Looping Objects: Object Keys, Values, and Entries", 10],
            ["CHALLENGE #2", 15],
            ["Sets", 13],
            ["New Operations to Make Sets Useful!", 16],
            ["Maps: Fundamentals", 14],
            ["Maps: Iteration", 13],
            ["Summary: Which Data Structure to Use?", 10],
            ["CHALLENGE #3", 10],
            ["Working With Strings - Part 1", 17],
            ["Working With Strings - Part 2", 22],
            ["Working With Strings - Part 3", 22],
            ["CHALLENGE #4", 15],
            ["String Methods Practice", 17],
          ]),
          mkModule("js-oop", "Section 10: A Closer Look at Functions", [
            ["Section Intro", 1],
            ["Section Roadmap", 1],
            ["Default Parameters", 9],
            ["How Passing Arguments Works: Value vs. Reference", 14],
            ["First-Class and Higher-Order Functions", 5],
            ["Functions Accepting Callback Functions", 15],
            ["Functions Returning Functions", 7],
            ["The call and apply Methods", 17],
            ["The bind Method", 21],
            ["CHALLENGE #1", 19],
            ["Immediately Invoked Function Expressions (IIFE)", 8],
            ["Closures", 22],
            ["More Closure Examples", 16],
            ["CHALLENGE #2", 5],
          ]),
          mkModule("js-oop", "Section 11: Working With Arrays [PROJECT]", [
            ["Section Roadmap", 1],
            ["Simple Array Methods", 17],
            ["The New at Method", 6],
            ["Looping Arrays: forEach", 14],
            ["forEach With Maps and Sets", 6],
            ['PROJECT: "Bankist" App', 10],
            ["Creating DOM Elements", 19],
            ["CHALLENGE #1", 9],
            ["Data Transformations: map, filter, reduce", 5],
            ["The map Method", 16],
            ["Computing Usernames", 12],
            ["The filter Method", 6],
            ["The reduce Method", 21],
            ["CHALLENGE #2", 10],
            ["The Magic of Chaining Methods", 20],
            ["CHALLENGE #3", 4],
            ["The find Method", 7],
            ["Implementing Login", 24],
            ["Implementing Transfers", 21],
            ["The findIndex Method", 13],
            ["The New findLast and findLastIndex Methods", 8],
            ["some and every", 15],
            ["flat and flatMap", 10],
            ["CHALLENGE #4", 24],
            ["Sorting Arrays", 22],
            ["Array Grouping", 13],
            ["More Ways of Creating and Filling Arrays", 21],
            ["Non-Destructive Alternatives: toReversed, toSorted, toSpliced, with", 6],
            ["Summary: Which Array Method to Use?", 11],
            ["Array Methods Practice", 32],
            ["CHALLENGE #5", 29],
          ]),
          mkModule("js-oop", "Section 12: Numbers, Dates, Intl and Timers [PROJECT]", [
            ["Section Intro", 1],
            ["Section Roadmap", 1],
            ["Converting and Checking Numbers", 17],
            ["Math and Rounding", 23],
            ["The Remainder Operator", 11],
            ["Numeric Separators", 7],
            ["Working with BigInt", 11],
            ["Creating Dates", 13],
            ['Adding Dates to "Bankist" App', 22],
            ["Fixing a Sorting Bug", 11],
            ["Operations With Dates", 15],
            ["Internationalizing Dates (Intl)", 17],
            ["Internationalizing Numbers (Intl)", 19],
            ["Timers: setTimeout and setInterval", 14],
            ["Implementing a Countdown Timer", 18],
          ]),
          mkModule("js-oop", "Section 13: Advanced DOM and Events [PROJECT]", [
            ["Section Intro", 1],
            ["Section Roadmap", 1],
            ['PROJECT: "Bankist" Website', 9],
            ["How the DOM Really Works", 11],
            ["Selecting, Creating, and Deleting Elements", 20],
            ["Styles, Attributes and Classes", 22],
            ["Implementing Smooth Scrolling", 16],
            ["Types of Events and Event Handlers", 10],
            ["Event Propagation: Bubbling and Capturing", 5],
            ["Event Propagation in Practice", 18],
            ["Event Delegation: Implementing Page Navigation", 19],
            ["DOM Traversing", 15],
            ["Building a Tabbed Component", 24],
            ["Passing Arguments to Event Handlers", 19],
            ["Implementing a Sticky Navigation: The Scroll Event", 8],
            ["A Better Way: The Intersection Observer API", 24],
            ["Revealing Elements on Scroll", 13],
            ["Fixing a Small Scrolling Bug", 5],
            ["Lazy Loading Images", 19],
            ["Building a Slider Component: Part 1", 23],
            ["Building a Slider Component: Part 2", 20],
            ["Lifecycle DOM Events", 9],
            ["Efficient Script Loading: defer and async", 14],
          ]),
          mkModule("js-oop", "Section 14: Object-Oriented Programming OOP with JavaScript", [
            ["Section Intro", 1],
            ["Section Roadmap", 1],
            ["What is Object-Oriented Programming?", 21],
            ["OOP in JavaScript", 10],
            ["Constructor Functions and the new Operator", 14],
            ["Prototypes", 15],
            ["Prototypal Inheritance and The Prototype Chain", 11],
            ["Prototypal Inheritance on Built-In Objects", 15],
            ["CHALLENGE #1", 7],
            ["ES6 Classes", 13],
            ["Setters and Getters", 13],
            ["Static Methods", 6],
            ["Object.create", 11],
            ["CHALLENGE #2", 6],
            ['Inheritance Between "Classes": Constructor Functions', 21],
            ["CHALLENGE #3", 11],
            ['Inheritance Between "Classes": ES6 Classes', 11],
            ['Inheritance Between "Classes": Object.create', 9],
            ["Another Class Example", 11],
            ["Encapsulation: Private Class Fields and Methods", 21],
            ["Chaining Methods", 7],
            ["ES6 Classes Summary", 7],
            ["CHALLENGE #4", 9],
          ]),
          mkModule(
            "js-oop",
            "Section 15: Mapty App: OOP, Geolocation, External Libraries, and More! [PROJECT]",
            [
              ["Section Intro", 1],
              ["Section Roadmap", 1],
              ["Project Overview", 5],
              ["How to Plan a Web Project", 18],
              ["Help Maya Plan a Project", 18],
              ["Using the Geolocation API", 8],
              ["Displaying a Map Using Leaflet Library", 14],
              ["Displaying a Map Marker", 20],
              ["Rendering Workout Input Form", 17],
              ["Project Architecture", 9],
              ["Refactoring for Project Architecture", 24],
              ["Managing Workout Data: Creating Classes", 16],
              ["Creating a New Workout", 34],
              ["Rendering Workouts", 24],
              ["Move to Marker On Click", 17],
              ["Working with localStorage", 26],
              ["Final Considerations", 6],
            ],
          ),
          mkModule("js-oop", "Section 16: Async JS: Promises, Async/Await, and AJAX", [
            ["Section Intro", 1],
            ["Section Roadmap", 1],
            ["Asynchronous JavaScript, AJAX and APIs", 18],
            ["IMPORTANT: API URL Change", 1],
            ["Our First AJAX Call: XMLHttpRequest", 20],
            ["[OPTIONAL] How the Web Works: Requests and Responses", 14],
            ["Welcome to Callback Hell", 14],
            ["Promises and the Fetch API", 9],
            ["Consuming Promises", 9],
            ["Chaining Promises", 9],
            ["Handling Rejected Promises", 16],
            ["Throwing Errors Manually", 15],
            ["CHALLENGE #1", 17],
            ["Asynchronous Behind the Scenes: The Event Loop", 18],
            ["The Event Loop in Practice", 9],
            ["Building a Simple Promise", 20],
            ["Promisifying the Geolocation API", 13],
            ["CHALLENGE #2", 16],
            ["Consuming Promises with Async/Await", 15],
            ["Error Handling With try...catch", 10],
            ["Returning Values from Async Functions", 15],
            ["Running Promises in Parallel", 11],
            ["Other Promise Combinators: race, allSettled and any", 13],
            ["CHALLENGE #3", 18],
          ]),
          mkModule(
            "js-oop",
            "Section 17: Modern JavaScript Development: Modules, Tooling and Functional",
            [
              ["Section Intro", 1],
              ["Section Roadmap", 1],
              ["An Overview of Modern JavaScript Development", 7],
              ["An Overview of Modules in JavaScript", 15],
              ["Exporting and Importing in ES6 Modules", 23],
              ["Top-Level await (ES2022)", 15],
              ["The Module Pattern", 10],
              ["CommonJS Modules", 4],
              ["A Brief Introduction to the Command Line", 12],
              ["Introduction to NPM", 19],
              ["Bundling With Parcel and NPM Scripts", 22],
              ["Configuring Babel and Polyfilling", 18],
              ["Review: Writing Clean and Modern JavaScript", 10],
              ["Let's Fix Some Bad Code: Part 1", 23],
              ["Declarative and Functional JavaScript Principles", 12],
              ["Let's Fix Some Bad Code: Part 2", 38],
            ],
          ),
          mkModule("js-oop", "Section 18: Forkify App: Building a Modern Application [PROJECT]", [
            ["Section Intro", 1],
            ["Section Roadmap", 1],
            ["Project Overview and Planning (I)", 14],
            ["Latest Code Updates (IMPORTANT!)", 1],
            ["Loading a Recipe from API", 24],
            ["Rendering the Recipe", 22],
            ["Listening For load and hashchange Events", 11],
            ["The MVC Architecture", 17],
            ["Refactoring for MVC", 39],
            ["Helpers and Configuration Files", 21],
            ["Event Handlers in MVC: Publisher-Subscriber Pattern", 15],
            ["Implementing Error and Success Messages", 12],
            ["Implementing Search Results - Part 1", 26],
            ["Implementing Search Results - Part 2", 28],
            ["Implementing Pagination - Part 1", 12],
            ["Implementing Pagination - Part 2", 37],
            ["Project Planning II", 3],
            ["Updating Recipe Servings", 27],
            ["Developing a DOM Updating Algorithm", 34],
            ["Implementing Bookmarks - Part 1", 26],
            ["Implementing Bookmarks - Part 2", 19],
            ["Storing Bookmarks With localStorage", 18],
            ["Project Planning III", 2],
            ["Uploading a New Recipe - Part 1", 18],
            ["Uploading a New Recipe - Part 2", 41],
            ["Uploading a New Recipe - Part 3", 20],
            ["Wrapping Up: Final Considerations", 15],
          ]),
          mkModule("js-oop", "Section 19: Setting Up Git and Deployment", [
            ["Section Intro", 1],
            ["Section Roadmap", 1],
            ["Simple Deployment With Netlify", 11],
            ["Setting Up Git and GitHub", 8],
            ["Git Fundamentals", 20],
            ["Pushing to GitHub", 10],
            ["Setting Up Continuous Integration With Netlify", 18],
          ]),
        ],
      },
    ],
    assessment: buildAssessment(jsQuestions, "JavaScript"),
    project: {
      id: "p1",
      title: "Bankist — Banking UI",
      description:
        "Build a beautiful banking interface app with transfers, loans, and timers in vanilla JS.",
      difficulty: "Medium",
      estimatedHours: 24,
      skills: ["DOM", "Async", "OOP", "Arrays"],
      requirements: [
        "Login flow",
        "Transfer money",
        "Request loan",
        "Account summary",
        "Auto-logout timer",
        "Sort transactions",
      ],
    },
  },
  {
    id: 2,
    title: "React Ecosystem",
    subtitle: "React, Next.js & Redux",
    description:
      "Master component-driven UIs, routing, server rendering, and predictable state management.",
    courses: [
      {
        id: "react",
        title: "React",
        modules: [
          mkModule("r-fund", "React Fundamentals", [
            ["JSX", 18],
            ["Components", 22],
            ["Props", 18],
            ["State & hooks", 30],
            ["Effects", 26],
          ]),
          mkModule("r-adv", "Advanced Patterns", [
            ["Context", 22],
            ["Custom hooks", 28],
            ["Memoization", 24],
            ["Suspense", 20],
          ]),
        ],
      },
      {
        id: "next",
        title: "Next.js",
        modules: [
          mkModule("n-fund", "App Router", [
            ["Routing", 22],
            ["Server components", 30],
            ["Data fetching", 28],
            ["Server actions", 25],
          ]),
          mkModule("n-prod", "Production", [
            ["Caching", 22],
            ["Deployment", 18],
            ["Middleware", 22],
          ]),
        ],
      },
      {
        id: "redux",
        title: "Redux Toolkit",
        modules: [
          mkModule("rd-fund", "Redux", [
            ["Slices", 20],
            ["Async thunks", 24],
            ["RTK Query", 28],
            ["Selectors", 18],
          ]),
        ],
      },
    ],
    assessment: buildAssessment(jsQuestions, "React"),
    project: {
      id: "p2",
      title: "Workout Planner",
      description: "Full-stack React + Next.js workout tracker.",
      difficulty: "Medium",
      estimatedHours: 30,
      skills: ["React", "Next.js", "Redux"],
      requirements: ["Auth-less local store", "Routine builder", "Daily log", "Charts"],
    },
  },
  {
    id: 3,
    title: "TypeScript",
    subtitle: "Type-safe at scale",
    description: "Use TypeScript fluently across React apps, libraries, and complex domain models.",
    courses: [
      {
        id: "ts",
        title: "TypeScript Deep Dive",
        modules: [
          mkModule("ts-base", "Foundations", [
            ["Primitives & types", 22],
            ["Interfaces", 22],
            ["Generics", 30],
            ["Narrowing", 24],
          ]),
          mkModule("ts-adv", "Advanced", [
            ["Conditional types", 28],
            ["Mapped types", 26],
            ["Utility types", 22],
            ["TS + React", 30],
          ]),
        ],
      },
    ],
    assessment: buildAssessment(jsQuestions, "TypeScript"),
    project: {
      id: "p3",
      title: "Type-safe API SDK",
      description: "Build a fully typed SDK with generics, narrowing, and Zod.",
      difficulty: "Medium",
      estimatedHours: 22,
      skills: ["TypeScript", "Zod"],
      requirements: ["Branded types", "Inferred client", "Error model", "Tests"],
    },
  },
  {
    id: 4,
    title: "Backend Engineering",
    subtitle: "Node, Express, Postgres, Prisma",
    description: "Design APIs, model relational data, and ship reliable backend services.",
    courses: [
      {
        id: "node",
        title: "Node.js + Express",
        modules: [
          mkModule("node-base", "Node Core", [
            ["Modules", 18],
            ["Streams", 22],
            ["File system", 18],
          ]),
          mkModule("exp", "Express", [
            ["Routing", 18],
            ["Middleware", 22],
            ["Validation", 18],
            ["REST design", 24],
          ]),
        ],
      },
      {
        id: "pg",
        title: "PostgreSQL + Prisma",
        modules: [
          mkModule("pg-base", "Postgres", [
            ["SQL basics", 24],
            ["Joins & indexes", 28],
            ["Transactions", 20],
          ]),
          mkModule("prisma", "Prisma", [
            ["Schema", 18],
            ["Migrations", 18],
            ["Queries", 22],
          ]),
        ],
      },
    ],
    assessment: buildAssessment(jsQuestions, "Backend"),
    project: {
      id: "p4",
      title: "Realtime Issue Tracker API",
      description: "Express + Prisma + Postgres API with auth-less seed data.",
      difficulty: "Hard",
      estimatedHours: 32,
      skills: ["Node", "Express", "Postgres", "Prisma"],
      requirements: ["CRUD", "Pagination", "Search", "Migrations"],
    },
  },
  {
    id: 5,
    title: "Auth, Testing & Hardening",
    subtitle: "Production-grade backends",
    description: "Secure systems, comprehensive testing, and resilient backend patterns.",
    courses: [
      {
        id: "auth",
        title: "Authentication",
        modules: [
          mkModule("a-base", "Auth Concepts", [
            ["Sessions vs JWT", 22],
            ["OAuth", 24],
            ["Password hashing", 18],
          ]),
        ],
      },
      {
        id: "test",
        title: "Testing",
        modules: [
          mkModule("t-base", "Testing Pyramid", [
            ["Unit testing", 24],
            ["Integration", 22],
            ["E2E with Playwright", 28],
          ]),
        ],
      },
      {
        id: "hard",
        title: "Hardening",
        modules: [
          mkModule("h-base", "Production Ready", [
            ["Rate limiting", 18],
            ["CSRF / CORS", 18],
            ["Observability", 22],
          ]),
        ],
      },
    ],
    assessment: buildAssessment(jsQuestions, "Security"),
    project: {
      id: "p5",
      title: "Hardened SaaS Starter",
      description: "Auth-protected SaaS template with tests and observability.",
      difficulty: "Hard",
      estimatedHours: 36,
      skills: ["Auth", "Testing", "Security"],
      requirements: ["Auth flows", "Rate limit", "Tests >80% coverage"],
    },
  },
  {
    id: 6,
    title: "System Design & DevOps",
    subtitle: "Scale & ship reliably",
    description: "Design distributed systems and operate them with modern DevOps tooling.",
    courses: [
      {
        id: "sd",
        title: "System Design",
        modules: [
          mkModule("sd-base", "Foundations", [
            ["Scalability", 28],
            ["Caching", 22],
            ["Queues", 22],
            ["Sharding", 26],
          ]),
        ],
      },
      {
        id: "do",
        title: "DevOps",
        modules: [
          mkModule("do-base", "CI/CD & Infra", [
            ["Docker", 24],
            ["GitHub Actions", 20],
            ["Cloudflare/Vercel", 22],
            ["Monitoring", 22],
          ]),
        ],
      },
    ],
    assessment: buildAssessment(jsQuestions, "System Design"),
    project: {
      id: "p6",
      title: "Designed-for-Scale URL Shortener",
      description: "Build with caching, queue, and observability.",
      difficulty: "Hard",
      estimatedHours: 30,
      skills: ["System Design", "DevOps"],
      requirements: ["100k req/s plan", "Cache layer", "Metrics dashboard"],
    },
  },
  {
    id: 7,
    title: "Flagship Project",
    subtitle: "Capstone build",
    description: "Ship a portfolio-grade product. Weekly milestones, no assessment.",
    courses: [
      {
        id: "flag",
        title: "Flagship Build",
        modules: [
          mkModule("w1", "Week 1 — Scope & Design", [
            ["Define product", 60],
            ["Wireframes", 90],
            ["Tech plan", 60],
          ]),
          mkModule("w2", "Week 2 — Core", [
            ["Data model", 90],
            ["Core flows", 120],
            ["Auth", 60],
          ]),
          mkModule("w3", "Week 3 — Polish", [
            ["Edge cases", 90],
            ["Performance", 60],
            ["A11y pass", 60],
          ]),
          mkModule("w4", "Week 4 — Launch", [
            ["Tests", 90],
            ["Deploy", 60],
            ["Marketing page", 90],
          ]),
        ],
      },
    ],
    project: {
      id: "p7",
      title: "Final Project Review",
      description: "Self-review, write a launch post, record a demo.",
      difficulty: "Hard",
      estimatedHours: 12,
      skills: ["Everything"],
      requirements: ["Demo video", "Launch post", "Retrospective"],
    },
  },
  {
    id: 8,
    title: "Interview Prep & Job Search",
    subtitle: "Land the role",
    description: "Resume, portfolio, applications, interviews, offers.",
    courses: [
      {
        id: "prep",
        title: "Interview Prep",
        modules: [
          mkModule("res", "Resume & Portfolio", [
            ["Resume polish", 60],
            ["Portfolio polish", 90],
            ["LinkedIn", 45],
          ]),
          mkModule("apps", "Applications", [
            ["Wishlist 30 companies", 60],
            ["Daily applications", 120],
            ["Recruiter outreach", 60],
          ]),
          mkModule("mock", "Mock Interviews", [
            ["Behavioral", 60],
            ["System design", 90],
            ["Coding rounds", 120],
          ]),
          mkModule("off", "Offers", [
            ["Negotiation", 45],
            ["Decision", 30],
          ]),
        ],
      },
    ],
  },
];

export const ALL_LECTURE_IDS = MONTHS.flatMap((m) =>
  m.courses.flatMap((c) => c.modules.flatMap((mod) => mod.lectures.map((l) => l.id))),
);
export const TOTAL_LECTURES = ALL_LECTURE_IDS.length;
export const TOTAL_MINUTES = MONTHS.reduce(
  (acc, m) =>
    acc +
    m.courses.reduce(
      (a, c) =>
        a + c.modules.reduce((b, mod) => b + mod.lectures.reduce((s, l) => s + l.minutes, 0), 0),
      0,
    ),
  0,
);
