/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatisticsRouteImport } from './routes/statistics'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectMonthIdRouteImport } from './routes/project.$monthId'
import { Route as MonthIdRouteImport } from './routes/month.$id'
import { Route as AssessmentMonthIdRouteImport } from './routes/assessment.$monthId'

const StatisticsRoute = StatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectMonthIdRoute = ProjectMonthIdRouteImport.update({
  id: '/project/$monthId',
  path: '/project/$monthId',
  getParentRoute: () => rootRouteImport,
} as any)
const MonthIdRoute = MonthIdRouteImport.update({
  id: '/month/$id',
  path: '/month/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentMonthIdRoute = AssessmentMonthIdRouteImport.update({
  id: '/assessment/$monthId',
  path: '/assessment/$monthId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/calendar': typeof CalendarRoute
  '/login': typeof LoginRoute
  '/practice': typeof PracticeRoute
  '/roadmap': typeof RoadmapRoute
  '/settings': typeof SettingsRoute
  '/statistics': typeof StatisticsRoute
  '/assessment/$monthId': typeof AssessmentMonthIdRoute
  '/month/$id': typeof MonthIdRoute
  '/project/$monthId': typeof ProjectMonthIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/calendar': typeof CalendarRoute
  '/login': typeof LoginRoute
  '/practice': typeof PracticeRoute
  '/roadmap': typeof RoadmapRoute
  '/settings': typeof SettingsRoute
  '/statistics': typeof StatisticsRoute
  '/assessment/$monthId': typeof AssessmentMonthIdRoute
  '/month/$id': typeof MonthIdRoute
  '/project/$monthId': typeof ProjectMonthIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/calendar': typeof CalendarRoute
  '/login': typeof LoginRoute
  '/practice': typeof PracticeRoute
  '/roadmap': typeof RoadmapRoute
  '/settings': typeof SettingsRoute
  '/statistics': typeof StatisticsRoute
  '/assessment/$monthId': typeof AssessmentMonthIdRoute
  '/month/$id': typeof MonthIdRoute
  '/project/$monthId': typeof ProjectMonthIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/achievements'
    | '/calendar'
    | '/login'
    | '/practice'
    | '/roadmap'
    | '/settings'
    | '/statistics'
    | '/assessment/$monthId'
    | '/month/$id'
    | '/project/$monthId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/achievements'
    | '/calendar'
    | '/login'
    | '/practice'
    | '/roadmap'
    | '/settings'
    | '/statistics'
    | '/assessment/$monthId'
    | '/month/$id'
    | '/project/$monthId'
  id:
    | '__root__'
    | '/'
    | '/achievements'
    | '/calendar'
    | '/login'
    | '/practice'
    | '/roadmap'
    | '/settings'
    | '/statistics'
    | '/assessment/$monthId'
    | '/month/$id'
    | '/project/$monthId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AchievementsRoute: typeof AchievementsRoute
  CalendarRoute: typeof CalendarRoute
  LoginRoute: typeof LoginRoute
  PracticeRoute: typeof PracticeRoute
  RoadmapRoute: typeof RoadmapRoute
  SettingsRoute: typeof SettingsRoute
  StatisticsRoute: typeof StatisticsRoute
  AssessmentMonthIdRoute: typeof AssessmentMonthIdRoute
  MonthIdRoute: typeof MonthIdRoute
  ProjectMonthIdRoute: typeof ProjectMonthIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/statistics': {
      id: '/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof StatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$monthId': {
      id: '/project/$monthId'
      path: '/project/$monthId'
      fullPath: '/project/$monthId'
      preLoaderRoute: typeof ProjectMonthIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/month/$id': {
      id: '/month/$id'
      path: '/month/$id'
      fullPath: '/month/$id'
      preLoaderRoute: typeof MonthIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/$monthId': {
      id: '/assessment/$monthId'
      path: '/assessment/$monthId'
      fullPath: '/assessment/$monthId'
      preLoaderRoute: typeof AssessmentMonthIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AchievementsRoute: AchievementsRoute,
  CalendarRoute: CalendarRoute,
  LoginRoute: LoginRoute,
  PracticeRoute: PracticeRoute,
  RoadmapRoute: RoadmapRoute,
  SettingsRoute: SettingsRoute,
  StatisticsRoute: StatisticsRoute,
  AssessmentMonthIdRoute: AssessmentMonthIdRoute,
  MonthIdRoute: MonthIdRoute,
  ProjectMonthIdRoute: ProjectMonthIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
